import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/header.module.css'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export default function Contact() {

  function sendEmail() {
    const form = document.getElementById('form')

    form.addEventListener('submit', _ => _.preventDefault())

    const nome = document.getElementById('nome').value
    const email = document.getElementById('email').value
    const telefone = document.getElementById('telefone').value
    const assunto = document.getElementById('assunto').value
    const mensagem = document.getElementById('mensagem').value

    fetch('api/hello', {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        nome,
        email,
        telefone,
        assunto,
        mensagem
      })
    }).then(response => {
      console.log(response)
      alert('Email enviado com sucesso!')
    }).catch(error => {
      console.log(error)
      alert('Ocorreu um erro')
    })

  }


  return (
    <>
      <Head>
        <title>Fale Conosco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div className={`text-white ${styles.header}`}>
          <div className="container mx-auto px-12 pt-24 pb-10">
            <div className="grid grid-cols-12">
              <div className="md:invisible col-span-12 md:col-span-4 flex items-center mx-auto md:order-2">
                <FontAwesomeIcon icon="fa-solid fa-envelope" size='6x' />
              </div>
              <div className="col-span-12 md:order-1">
                <h1 className="text-cinzaastro-300 text-center md:text-left leading-none font-light text-4xl my-4 md:mb-4">Fale conosco</h1>
                <p className="text-justify text-amareloastro-700">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam assumenda quod culpa velit, nihil enim ipsum quam possimus, a veritatis tempora odit! Commodi, quos. Quisquam animi adipisci architecto repudiandae numquam.</p>
              </div>
            </div>

            <div>

              <h1 className="text-cinzaastro-300 text-center md:text-left leading-none font-light text-2xl my-8 md:my-4">Preencha os dados abaixo:</h1>

              <div className="grid grid-cols-12 gap-4 mt-4">
                <div className="col-span-12 md:col-span-6">
                  <form id='form'>

                    <div className="form-group mb-6">

                      <label htmlFor="nome" className="form-label inline-block mb-2 text-amareloastro-500">Nome completo*</label>

                      <input type="text" className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" id="nome" placeholder="Digite seu nome" />

                    </div>

                    <div className="form-group mb-6">

                      <label htmlFor="email" className="form-label inline-block mb-2 text-amareloastro-500">E-mail*</label>

                      <input type="text" className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" id="email" placeholder="Digite seu e-mail" />

                    </div>

                    <div className="grid grid-cols-2 gap-4">
                      <div className="col-span-2 md:col-span-1 form-group mb-6">

                        <label htmlFor="telefone" className="form-label inline-block mb-2 text-amareloastro-500">Telefone*</label>

                        <input type="text" className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" id="telefone" placeholder="Digite seu principal telefone" />

                      </div>

                      <div className="col-span-2 md:col-span-1 form-group mb-6">

                        <label htmlFor="assunto" className="form-label inline-block mb-2 text-amareloastro-500">Assunto*</label>

                        <div className="flex">
                          <div className="mb-3 w-full">
                            <select className="form-select block w-full px-3 py-1.5 text-base text-gray-700 bg-white bg-clip-padding bg-no-repeat border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" aria-label="Default select example" id='assunto'>
                              <option selected>Escolhe o tipo de assunto:</option>
                              <option value="Matrícula">Matrícula</option>
                              <option value="Elogio">Elogio</option>
                              <option value="Reclamações">Reclamações</option>
                              <option value="Dúvidas">Dúvidas</option>
                              <option value="Sugestões">Sugestões</option>
                            </select>
                          </div>
                        </div>
                      </div>
                    </div>

                  </form>
                </div>

                <div className="col-span-12 md:col-span-6">
                  <div className="form-group mb-6">

                    <label htmlFor="mensagem" className="form-label inline-block mb-2 text-amareloastro-500">Mensagem*</label>

                    <textarea className="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" id="mensagem" rows="7" placeholder="Escreva aqui..." required ></textarea>

                    <button onClick={sendEmail} type="button" className="mt-2 w-full  px-6 py-2.5 bg-yellow-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-yellow-600 hover:shadow-lg focus:bg-yellow-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-700 active:shadow-lg transition duration-150 ease-in-out">Enviar</button>

                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </body>
    </>
  )
}
