import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Section01 from '../components/section01'
import Section02 from '../components/section02'
import Section03 from '../components/section03'
import Section04 from '../components/section04'

export default function Home() {

  return (
    <>
      <Head>
        <title>AstroCrypto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Header />
        <Section02 />
        <Section03 />
        <Section01 />
        <Section04 />
      </body>
    </>
  )
}
