import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/nav'
import Header from '../components/header'
import Vantagens from '../components/vantagens'
import Conheca from '../components/conheca'
import Sobre from '../components/sobre'
import Depoimentos from '../components/depoimentos'

export default function Home() {

  return (
    <>
      <Head>
        <title>AstroCrypto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Nav />
        <Header />
        <Conheca />
        <Sobre />
        <Vantagens />
        <Depoimentos />
      </body>
    </>
  )
}
