import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/header.module.css'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import NavContact from '../components/navContact'

export default function Contact() {


  return (
    <>
      <Head>
        <title>Termo de privacidade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <NavContact />
        <div className={`text-white ${styles.header}`}>
          <div className="container mx-auto px-12 pt-18 pb-10">
            <div className="grid grid-cols-12">
              <div className="md:invisible col-span-12 md:col-span-4 flex items-center mx-auto md:order-2">
                <FontAwesomeIcon icon="fa-solid fa-file-lines" />
              </div>
              <div className={`col-span-12 md:order-1 text-justify ${styles.textPolitica}`}>
                <h1 className="text-cinzaastro-300 text-center md:text-left leading-none font-light text-4xl my-4 md:mb-4">Termo de políticas de Privacidade</h1>
                <p className="text-amareloastro-700 mb-6">A empresa HP HOLDING PARTICIPACOES LTDA., pessoa jurídica de direito privado regida pelas leis brasileiras, inscrita no CNPJ sob o nº 34.179.467/0001- 62, com sede em: Rua Miguel de Frias, 77, salas: 1501, 1502 e 1503, Icaraí – Niterói, RJ, está comprometida em proteger e respeitar a privacidade de usuários:</p>
                <p>
                  Esta política, acompanhado de nossos Termos e Condições de Uso do Site
                  estabelece a base sobre a qual qualquer informação pessoal que coletarmos de você, ou que você nos fornece,
                  será processada por nós.
                </p>
                <p>
                  Esta Política de Privacidade se aplica às informações que coletamos dos usuários quando os mesmos acessam ou
                  utilizam nossos serviços através do site ou aplicativo.
                </p>
                <p>
                  Leia cuidadosamente o seguinte para entender nossas opiniões e práticas sobre suas informações
                  pessoais e como vamos tratá-las. Ao visitar o site, o usuário está aceitando e concordando com as práticas
                  descritas nesta política.
                </p>
                <p>
                  Nosso site pode, de tempos em tempos, conter links de e para os sites de nossas redes de parceiros,
                  anunciantes e afiliados. Se o usuário seguir um link para qualquer um desses sites, deverá observar que
                  esses sites têm suas próprias políticas de privacidade e que não possuímos nenhuma responsabilidade por
                  essas políticas.
                </p>
                <p>
                  Verifique estas políticas antes de enviar quaisquer dados pessoais para esses sites.
                  Os serviços da HP HOLDING estão sujeitos à sua Política de Privacidade, a qual tem por objetivo atender aos
                  princípios da LGPD, especialmente no que tange às finalidades de como e para quais finalidades os dados
                  pessoais são tratados; com quem esses dados pessoais podem ser compartilhados; e como os Usuários podem
                  gerenciar seus dados pessoais.
                </p>
                <p>O tratamento dos dados pessoais é condição para utilizar HP HOLDING. Não é possível oferecer as
                  funcionalidades da Plataforma sem ter acesso a esses dados pessoais.
                </p>
                <h6 className='text-amareloastro-500 text-xl'>Informações sobre coleta de dados</h6>
                <p>Aos usuários da Plataforma poderão ser solicitados o fornecimento de informações pessoais sempre que os
                  mesmos efetuarem o cadastro dentro no nosso Website. A HP HOLDING pode compartilhar essas informações
                  pessoais e usá-las de maneira consistente com a Política de Privacidade.
                </p>
                <p>
                  A HP HOLDING processa os dados pessoais dos usuários conforme necessário para cumprir suas obrigações legais
                  e contratuais, operar negócios, fornecer serviços que os usuários utilizam ou de outra forma a cumprir os
                  interesses legítimos descritos nas seções Uso das informações abaixo.
                  Podemos coletar e processar os seguintes dados dos usuários:
                </p>
                <ol>
                  <li>
                    <dt className='text-amareloastro-500'>1. Informações que você nos fornece:</dt>
                    <ol>
                      <li><span className='ml-4 text-amareloastro-500'>1.1.</span> Inscrição: Para se inscrever no site e receber informações, você precisa nos fornecer seu
                        endereço de e-mail.</li>
                      <li className='ml-4'><span className=' text-amareloastro-500'>1.2.</span>Cadastro: Para criar uma conta, o usuário precisa fornecer dados, incluindo seu nome completo,
                        nome da empresa (se aplicável), data de nascimento, contato telefônico e endereço de e-mail,
                        senha ou outros detalhes para ajudá-lo com sua experiência. Se você optou por não fornecer
                        informações mencionadas acima, não poderemos fornecer serviços ou produtos.
                      </li>
                      <li className='ml-4'><span className='text-amareloastro-500'>1.3.</span>Informações da sua conta: Podemos solicitar informações de contato, incluindo seu nome, nome da
                        empresa (se aplicável), endereço de e-mail, senha, data de nascimento, endereço e outros
                        detalhes para ajudá-lo com sua experiência.
                      </li>
                      <li className='ml-4'><span className=' text-amareloastro-500'>1.4.</span>Informação de pagamento: Quando o usuário adiciona suas informações de conta financeira à sua
                        conta ou usa nossos serviços ou acessa nosso site, essas informações (inclusive a dos outros
                        participantes associados à transação) são armazenadas de forma segura.
                      </li>
                      <li className='ml-4'><span className=' text-amareloastro-500'>1.5.</span>
                        Comunicações e suporte ao cliente: Se o usuário entrar em contato conosco, poderemos receber
                        informações como seu nome, endereço de e-mail,
                        número de telefone, o conteúdo da mensagem e / ou anexos que você pode nos enviar e qualquer
                        outra informação que você possa escolher fornecer.

                      </li>
                    </ol>
                  </li>
                  <li>
                    <dt className='text-amareloastro-500'>2. Informações que coletamos sobre os usuários:</dt>
                    <ol>
                      <li className='ml-4'><span className=' text-amareloastro-500'>2.1.</span>Cookies e outras tecnologias de rastreamento: A HP HOLDING utiliza cookies. Cookies são arquivos
                        de texto contendo pequenas quantidades de informações
                        que são baixadas para o seu dispositivo quando você visita um site. Os cookies são enviados de
                        volta ao site de origem em cada visita subsequente.
                        Podemos usar os seguintes cookies:
                        <ol>
                          <li className='ml-6'><span className=' text-amareloastro-500'>2.1.1.</span>Cookies estritamente necessários: Esses cookies são essenciais para que o usuário possa
                            navegar pelo site e usar seus recursos, como o acesso às áreas seguras do site;
                          </li>
                          <li className='ml-6'>
                            <span className=' text-amareloastro-500'>2.1.2.</span>Cookies analíticos / de desempenho: Eles permitem reconhecer e contar o número de
                            visitantes e ver como os visitantes se movimentam pelo nosso site quando o estão usando.
                            Isso nos ajuda a melhorar o funcionamento do nosso site, por exemplo, garantindo que os
                            usuários encontrem o que estão procurando com facilidade;
                          </li>
                          <li className='ml-6'>
                            <span className=' text-amareloastro-500'>2.1.3.</span>Cookies de funcionalidade: Estes são usados para reconhecê-lo quando você retornar ao
                            nosso site. Isso nos permite personalizar nosso conteúdo para você, cumprimentá-lo pelo
                            nome e lembre-se de suas preferências. Se desejar, o usuário poderá bloquear os cookies
                            ativando a configuração no seu navegador que permite recusar a configuração de todos ou
                            alguns cookies. No entanto, se o mesmo usar as configurações do seu navegador para
                            bloquear todos os cookies (incluindo cookies essenciais), poderá não conseguir acessar
                            todas ou partes das funcionalidades do nosso site.
                          </li>
                        </ol>
                      </li>
                    </ol>
                  </li>
                  <li>
                    <dt className='text-amareloastro-500'>3. Informações técnicas</dt>
                    <ol>
                      <li className='ml-4'><span className=' text-amareloastro-500'>3.1</span> Ao utilizar nossos Serviços, independentemente do dispositivo de onde os acessa, podemos
                        coletar informações sobre seu envolvimento e utilização de nossos Serviços, como o processador e
                        uso de memória, capacidade de armazenamento, navegação de nossas métricas de nível de sistema,
                        tipo de dispositivo, dados de uso do usuário, conexões de rede do dispositivo (por exemplo,
                        Wifi) e endereço IP (Internet Protocol), informações de geolocalização (por exemplo, GPS) e
                        catálogo biométrico. Dados.
                      </li>
                      <li className='ml-4'><span className=' text-amareloastro-500'>3.2</span>
                        Usamos esses dados para operar os Serviços, manter e melhorar o desempenho e a utilização dos
                        Serviços, desenvolver novos recursos, manter a segurança de nossos Serviços e nossos clientes.
                        Também usamos esses dados para desenvolver análises agregadas e business intelligence que nos
                        permitem operar, proteger, tomar decisões informadas e relatar o desempenho do nosso negócio.
                      </li>
                    </ol>
                  </li>
                </ol>
                <h6 className='text-amareloastro-500 text-xl'>Utilização das informações</h6>
                <p>
                  Usamos informações coletadas dos usuários das seguintes maneiras:
                </p>
                <ol>
                  <li>
                    <span className=' text-amareloastro-500'>1. </span>Para cumprir suas obrigações decorrentes da lei;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>2. </span>Cumprir obrigações decorrentes de quaisquer contratos celebrados entre usuário/empresa;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>3. </span>Operar e manter os Serviços, por exemplo, para autenticá-lo quando os usuários efetuarem login e para
                    processar as transações;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>4. </span>Prevenir, detectar e combater fraudes e gerenciar os riscos relacionados ao mesmo através do uso de
                    nosso
                    Site e Serviços (por exemplo, verificando sua identidade);
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>5. </span>Para fornecer aos usuários informações, produtos e serviços que os mesmos solicitam;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>6. </span>Para fornecer aos usuários informações sobre outros produtos e serviços que oferecemos, que são
                    semelhantes àqueles sobre os quais estes já perguntaram ou adquiriram;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>7. </span>Para se comunicar com os usuários, diretamente ou por meio de um dos nossos parceiros, inclusive para
                    atendimento ao mesmo, para responder às suas solicitações e para obter assistência e atendimento ao
                    cliente
                    serviço, para fornecer atualizações e outras informações relacionadas ao Serviço;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>8. </span>Para comunicar-se com você sobre nossos produtos e serviços ou notificá-lo sobre as alterações. Também
                    podemos usar suas informações para se comunicar com você sobre nossas promoções, estudos, pesquisas,
                    notícias, atualizações e eventos.
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>9. </span>Para melhorar o nosso site e garantir que o conteúdo do nosso site é apresentado da maneira mais eficaz
                    para você e para o seu computador.
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>10. </span>Para fins de conformidade, a fim de cumprir qualquer obrigação legal ou para aplicar ou aplicar os
                    Termos
                    e Condições do site e outros contratos; ou para proteger os direitos, propriedade ou segurança da
                    Empresa,
                    nossos clientes ou outros.
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>11. </span>Administrar nosso site e para operações internas, incluindo solução de problemas, análise de dados,
                    teste, pesquisa, estatística e pesquisa, ou para administrar um concurso, promoção, pesquisa ou outro
                    recurso do site.
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>12. </span>Para permitir que você participe de recursos interativos do nosso serviço, quando você optar por
                    fazê-lo;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>13. </span>Como parte de nossos esforços para manter nosso site seguro e protegido;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>14. </span> Para medir ou entender a eficácia da publicidade, podemos servir a você e fornecer publicidade relevante
                    para você. A HP HOLDING não comercializa ou negocia dados pessoais dos usuários;
                  </li>
                </ol>
                <h6 className='text-amareloastro-500 text-xl'>Mensagens comerciais</h6>
                <p>
                  Coletamos seu endereço de e-mail exclusivamente para:
                </p>
                <ol>
                  <li>
                    <span className=' text-amareloastro-500'>1. </span>Enviar informações, responder a consultas e / ou outras solicitações ou perguntas;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>2. </span>Processar ordens e enviar informações e atualizações relativas a pedidos;
                  </li>
                  <li>
                    <span className=' text-amareloastro-500'>3. </span>Também podemos enviar informações adicionais relacionadas ao seu produto e / ou serviço, bem como
                    newsletter.
                  </li>
                </ol>
                <h6 className='text-amareloastro-500 text-xl'>Trasnsparência de dados pessoais</h6>
                <p>
                  Departamento de Tecnologia, possui acesso geral ao site, podendo também ter acesso aos dados dos usuários
                  através dele.
                </p>
                <h6 className='text-amareloastro-500 text-xl'>Armazenamento</h6>
                <p>
                  Todas as informações que você nos fornece são armazenadas em nossos bancos de dados próprios protegidos com
                  os melhores métodos de segurança das informações.
                </p>
                <ol>
                  <li>
                    <dt className='text-amareloastro-500'>1. Ambiente</dt>
                    <ol>
                      <li>
                        Todas as informações que você nos fornece são armazenadas em nossos bancos de dados próprios
                        protegidos
                        com
                        os melhores métodos de segurança das informações.
                      </li>
                    </ol>
                  </li>
                  <li>
                    <dt className='text-amareloastro-500'>2. Duração</dt>
                    <ol>
                      <li>
                        Armazenamos as informações que coletamos sobre os usuários por não mais do que o necessário para
                        as
                        finalidades para as quais coletamos originalmente, a menos que um período de retenção mais longo
                        seja
                        exigido ou permitido pela lei aplicável e seja de nosso interesse comercial legítimo para fazer
                        isso.
                      </li>
                    </ol>
                  </li>
                  <li>
                    <dt className='text-amareloastro-500'>3. Segurança</dt>
                    <ol>
                      <li>
                        A HP HOLDING implementa medidas técnicas e organizacionais adequadas para garantir um nível de
                        segurança
                        adequado ao risco.
                      </li>
                    </ol>
                  </li>
                </ol>
              </div>
            </div>

          </div>
        </div>
      </body>
    </>
  )
}
